---
http_interactions:
- request:
    method: get
    uri: https://api360.yandex.net/directory/v1/org/1234567/groups/19
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v1.10.2
      Authorization:
      - TOKEN
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json
      Date:
      - Sat, 15 Oct 2022 10:08:52 GMT
      Grpc-Status:
      - '0'
      Grpc-Message:
      - OK
      Content-Length:
      - '291'
      Server:
      - api360
      X-Request-Id:
      - 968f7faa-de19-4a68-b712-05b6d5f699fe
    body:
      encoding: UTF-8
      string: '{"id":19,"name":"Hotline 247","type":"generic","description":"","membersCount":1,"label":"","email":"","aliases":[],"externalId":"","removed":false,"members":[{"type":"user","id":"48989999"}],"adminIds":["48989999"],"authorId":"48989999","memberOf":[],"createdAt":"2022-10-15T10:05:12.657Z"}'
  recorded_at: Sat, 15 Oct 2022 10:08:52 GMT
recorded_with: VCR 6.1.0
